sudo: false
language: elixir
matrix:
  include:
    - otp_release: 19.3
      elixir: 1.4.5
    - otp_release: 20.3
      elixir: 1.7.4
    - otp_release: 21.3
      elixir: 1.8.1
    - otp_release: 22.0
      elixir: 1.8.2
      env: LATEST=1
env:
  global:
    - MIX_ENV=test
script:
  - echo "===> Running with Erlang $TRAVIS_OTP_RELEASE";
    if [[ "$LATEST" == "1" ]]; then
      echo "===> Testing with code coverage";
      MIX_ENV=test mix coveralls.travis;
    else
      echo "===> Testing without code coverage";
      MIX_ENV=test mix test -- trace;
    fi

jobs:
  include:
    - stage: check_formatting
      if: env(LATEST) = 1
      script: mix format --check-formatted
